version: "3.5"
services:
  postgres:
    image: 'postgres:12'
    container_name: 'postgres_faraday'
    ports:
      - '54320:5432'
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data